"use client";

import Link from "next/link";
import { ArrowRight, Radar } from "lucide-react";

import { usePredictive } from "@/lib/hooks/useAnalytics";
import { SEVERITY_META } from "@/lib/utils/constants";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";

/**
 * Surfaces the top predictive alerts onto the Executive and Control Tower
 * dashboards. Renders nothing until predictions are available.
 */
export function PredictiveAlertsStrip({ context }: { context: "executive" | "control-tower" }) {
  const { data, isError } = usePredictive();
  if (isError || !data || data.alerts.length === 0) return null;

  const alerts = data.alerts.slice(0, 3);

  return (
    <Card className="border-l-4 border-l-brand-blue bg-brand-surface-2/40">
      <CardContent className="p-4">
        <div className="mb-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Radar className="size-4 text-brand-blue" />
            <h2 className="text-sm font-semibold text-foreground">Predictive alerts</h2>
            <Badge variant="muted">POC heuristic models</Badge>
          </div>
          <Link
            href="/predictive"
            className="inline-flex items-center gap-1 text-xs font-medium text-brand-blue hover:underline"
          >
            View all <ArrowRight className="size-3" />
          </Link>
        </div>
        <div className="grid gap-3 md:grid-cols-3">
          {alerts.map((a) => {
            const sev = SEVERITY_META[a.severity];
            return (
              <Link
                key={a.id}
                href={a.href}
                className="rounded-lg border border-border bg-card p-3 transition-colors hover:border-brand-blue"
                aria-label={a.title}
              >
                <div className="flex items-center justify-between gap-2">
                  <span className="text-sm font-semibold text-foreground">{a.title}</span>
                  <Badge variant={sev.variant}>{sev.label}</Badge>
                </div>
                <p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{a.detail}</p>
              </Link>
            );
          })}
        </div>
        {context === "executive" && (
          <p className="mt-2 text-[11px] text-muted-foreground">
            Predictions are generated by transparent heuristic models for demonstration purposes.
          </p>
        )}
      </CardContent>
    </Card>
  );
}
